os:
  - linux
  - osx

language: ruby
rvm:
  - 1.9.3
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-9.1.7.0

gemfile:
  - gemfiles/cuke_modeler0.gemfile
  - gemfiles/cuke_modeler1.gemfile

matrix:
  exclude:
    # Travis does not provide 1.9.3 on OSX
    - rvm: 1.9.3
      os: osx


script: bundle exec rake cuke_slicer:ci_build
